name: Validate
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: (cd web && yarn)
    - run: (cd web && yarn build)
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v3
      with:
        push: false
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: (cd web && yarn)
    - run: (cd web && yarn test)
    - run: (cd web && yarn build)
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.4'
    - run: go test
# TODO: run linter & pre-commit
